language: cpp

matrix:
  include:
    - os: linux
      compiler: clang

before_script:
  - source ./.travis/install_cmake.sh
  - source ./.travis/install_openssl.sh
  - source ./.travis/install_libsxg.sh

script:
  - install -d build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - ctest
