name: 'Release .deb files'
on: release

jobs:
  release-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_image: ["ubuntu:bionic", "ubuntu:disco", "ubuntu:eoan", "debian:buster"]
    steps:
      - uses: actions/checkout@v1

      - name: docker build with arg
        run: |
          mkdir -p output
          image_name=$(echo ${{matrix.base_image}} | cut -d: -f2 )
          docker build --build-arg base_image=${{ matrix.base_image }} -t ${image_name} -f packaging/deb.dockerfile .
          docker run --rm --mount "type=bind,source=$(pwd)/output,target=/nginx-sxg-module/output" ${image_name}
          zip -r libnginx-sxg-${{matrix.base_image}}.zip output
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: libnginx-sxg-${{matrix.base_image}}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
