name: 'Release .deb files'
on: release

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        names:
          - base_image: "ubuntu:bionic"
            image_name: "bionic"
          - base_image: "ubuntu:disco"
            image_name: "disco"
          - base_image: "ubuntu:eoan"
            image_name: "eoan"
          - base_image: "debian:buster"
            image_name: "buster"
    steps:
      - uses: actions/checkout@v1

      - name: docker build with arg
        run: |
          mkdir -p output
          docker build --build-arg base_image=${{ matrix.names.base_image }} -t ${{ matrix.names.image_name }} -f packaging/deb.dockerfile .
          docker run --rm --mount "type=bind,source=$(pwd)/output,target=/nginx-sxg-module/output" ${{ matrix.names.image_name }}
          zip -r libnginx-sxg-${{ matrix.names.image-name }}.zip output

      - name: Upload to release
        uses: kumagi/upload-to-release@v0.1.2
        with:
          args: libnginx-sxg-${{ matrix.names.image_name }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
